# Document:
url: https://solarex.github.io/wiki
title: Wiki·Solarex
keywords: android,linux,python,mac 
description: Solarex's personal wiki,powered by simiki.Focus on Android, Python, Linux, Mac and so on.
author: Solarex
theme: yasimple
